### ISSUE TITLE
License file not found

### ISSUE THREAD

**Issue by corop** [operatr-io/community#6]
for 

export LICENSE_LOCATION=/Users/asergeev/operatr.lic.txt

docker run -p 3000:3000 --env-file ./config.env operatr/operatr:latest

...
 Release: 41 // 2020-05-06-21-54

 License: None

 UI started on port 3000
...

11:29:50.037 INFO  [DefaultQuartzScheduler_Worker-2] operatr.compute ? no license provided.
-----------------
also for 

docker run -e LICENSE_LOCATION=/Users/asergeev/operatr.lic.txt -p 3000:3000 --env-file ./config.env operatr/operatr:latest

 > ls -al op*
-rw-rw-rw-  1 asergeev  staff  498 12 май 13:52 operatr.lic.txt

> pwd
/Users/asergeev

ERROR

11:25:24.597 ERROR [main] operatr.system ? failed to initialize :operatr/system: ./operatr.lic.txt (No such file or directory)
clojure.lang.ExceptionInfo: Error on key :operatr/system when building system

**Comment by d-t-w** [comment]
Hello Andrew,

You may need to map a docker volume to mount your local directory containing the operatr license to make it available to the container.

You don't need to do this with ./config.env file itself because --env-file manages the local-disk/container access in that case.

We will update our documentation to make this a bit clearer.

You can also configure the specific environment variables in your trial license email within config.env if you would rather not mount a volume for shared local/container disk access.

Derek

**Comment by d-t-w** [comment]
For example, given a license file in a relative path ./licenses/license.txt

```
$ ls -l ./licenses 

-rw-r--r--  1 derek  staff  518 31 Jan 11:00 license.txt
```

And an environment config file like:

```
$ cat docker/local.env

ENVIRONMENT_NAME=Trade Book (Staging)
BOOTSTRAP=kafka-1:19092,kafka-2:19093,kafka-3:19094
SECURITY_PROTOCOL=SASL_PLAINTEXT
SASL_MECHANISM=PLAIN
SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ALLOW_TOPIC_INSPECT=true
ALLOW_TOPIC_PRODUCE=true
ALLOW_TOPIC_EDIT=true
ALLOW_GROUP_EDIT=true
ALLOW_BROKER_EDIT=true
ALLOW_ACL_EDIT=false
ALLOW_UI_ANALYTICS=false
LICENSE_LOCATION=/licenses/license.txt
```

I can run the latest OPERATR with the following docker command (see the volume mount):

```bash
docker run --volume="$PWD/licenses:/licenses" -p 3000:3000 --env-file ./docker/local.env operatr/operatr:latest
```

**Comment by corop** [comment]
Thank you Derek! 

Now license load and working.

Thank you.
